const sticker = {
  like: "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/like.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvbGlrZS53ZWJwIiwiaWF0IjoxNzU2NzAyMTc4LCJleHAiOjE3NTczMDY5Nzh9.OGYQqKvXDQ2DCAs5SaL-Ys-WfUN6kRxU48ZszZIka_U",
  direction:
    "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/direction.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvZGlyZWN0aW9uLndlYnAiLCJpYXQiOjE3NTY3MDIxNTAsImV4cCI6MTc4ODIzODE1MH0.EEysCYmItI3ETP4asD2gFAmESL3cKy-OCAUZ1BsE7n8",
  contodo:
    "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/contodo.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvY29udG9kby53ZWJwIiwiaWF0IjoxNzU2NzAyMTM1LCJleHAiOjE3ODgyMzgxMzV9.rBYs-COMe_0cBwA2YDvlAeoBe-Gblasr0jyImVEpF5M",
  confirmacion:
    "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/confirmacion.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvY29uZmlybWFjaW9uLndlYnAiLCJpYXQiOjE3NTY3MDIxMTgsImV4cCI6MTc4ODIzODExOH0.gakXQhaWOd8B2sY89E1t6dJOGGaRvjCkVYS7em5bFUI",
  gracias:
    "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/gracias.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvZ3JhY2lhcy53ZWJwIiwiaWF0IjoxNzU2NzAyMTY1LCJleHAiOjE3ODgyMzgxNjV9.9kc_4dgSFaHcY4IHxQ8MN6nDp5AJ-MLf6QpczA-bLJU",
  menu: "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/menu.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvbWVudS5wbmciLCJpYXQiOjE3NTcwNDI1MTcsImV4cCI6MTc4ODU3ODUxN30.SZZiOJTbpqtcenMFA3B7IOHxw9JpqJ96HduoPghFGM0"};

const imagen = {
  menu: "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/menu.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvbWVudS5wbmciLCJpYXQiOjE3NTY3MDIwNTQsImV4cCI6MTc4ODIzODA1NH0.pjgp75ICq49NahEq88yYypZYYpwHNpVN8BjsOMO-A3g",
  logo: "https://nhdmbyxoyimcikenqcqu.supabase.co/storage/v1/object/sign/Assets/images.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9kODU3ZjhiYS02ZjFlLTRmM2UtYmY3Zi04MWZjNTg0MGUwZGEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJBc3NldHMvaW1hZ2VzLnBuZyIsImlhdCI6MTc1NjcwMjA5NCwiZXhwIjoxNzg4MjM4MDk0fQ.jcKeIiOqa9mV9JLZXbLvfT4m560we0oYAZCsPMMPbIk",
};

export { sticker, imagen };
